Pvwc mental health assessment
DalgoT4D/dbt_sneha pull request #58
Opened 2023-10-04 11:37 UTC by abikarmakar

2023-10-05 13:41 UTC, vinod-rajasekaran requested changes

2023-10-05 13:41 UTC, vinod-rajasekaran commented on models/intermediate/pvwc/int_pvwc_models.yml
can we remove commented lines to make this cleaner

2023-10-05 13:41 UTC, vinod-rajasekaran commented on models/intermediate/pvwc/pvwc_phq_gad_normalized.sql
can we remove unused fields here like reg_id, full name, centre etc that we are no pulling form case file ; also if not needed lets not import phq1-8 and gad1-8

2023-10-05 13:41 UTC, vinod-rajasekaran commented on models/production/pvwc/raw/pvwc_phq_gad.sql
more descriptive cte names please.

not understanding the two row numbers in cte a

why integer grades and then change them back to string again ?

we need to sit together and review - not super easy for me to look at

2023-10-06 05:27 UTC, abikarmakar commented on models/intermediate/pvwc/pvwc_phq_gad_normalized.sql
Done.

2023-10-06 05:28 UTC, abikarmakar commented on models/intermediate/pvwc/int_pvwc_models.yml
Done.

2023-10-06 10:10 UTC, abikarmakar commented on models/production/pvwc/raw/pvwc_phq_gad.sql
cte's given descripive names.

2023-10-12 04:45 UTC, vinod-rajasekaran requested changes

2023-10-12 05:44 UTC, abikarmakar commented on models/intermediate/pvwc/pvwc_phq_gad_normalized.sql
Done

2023-10-12 05:46 UTC, abikarmakar commented on models/intermediate/pvwc/pvwc_phq_gad_normalized.sql
Done.

2023-10-12 06:09 UTC, abikarmakar commented on models/intermediate/pvwc/pvwc_int_phq_gad.sql
Done.

2023-10-13 02:00 UTC, vinod-rajasekaran approved these changes

2023-10-13 02:00 UTC, merged